name: Continuous Benchmark

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, review_requested, ready_for_review]

jobs:
  bench:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/bench.yml
