name: Continuous Benchmark

on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
  pull_request:
    types: [opened, review_requested, synchronize, ready_for_review]
    branches: ["master", "dev"]

jobs:
  bench:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/bench.yml
