name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, review_requested, ready_for_review]

jobs:
  pre_job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "true"
          cancel_others: "true"

  cargo:
    if: github.event.pull_request.draft == false && needs.pre_job.outputs.should_skip != 'true'
    uses: ./.github/workflows/cargo.yml
  # tests:
  #   needs: [cargo]
  #   uses: ./.github/workflows/tests.yml
  # nix:
  #   needs: [cargo]
  #   uses: ./.github/workflows/nix.yml
